#!/usr/bin/env python3
"""M0/M1 conformance suite for the utter plugin protocol.

Starts the runner (``python -m runner --config <generated>``) with a config that
loads the Python and Rust fake plugins, then asserts the frozen handshake,
negotiation, the vertical slice, runner-enforced policy, cross-language
handshaking, and the M1 client API (streams, flow control, ``runner.invoke``,
``runner.validate_plugin``, handles/fd.pass, socket default-deny).

The client framing is implemented independently in ``framing_client.py`` — this
suite never imports the runner's framing code.

M1 features that the runner has not implemented yet are reported as
``NOT-YET-SUPPORTED`` (counted separately, never as failures), so the suite can
run against an M0 runner while the M1 lane lands.

Usage::

    .venv-agent/bin/python tests/conformance/run.py [--keep] [--timeout 30]

Exit code 0 = all assertions passed (or only not-yet-supported skips). If the
runner is absent the suite reports exactly which step blocked and exits 2.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import os
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(REPO / "tests"))

from framing_client import (  # noqa: E402
    ERR_HANDLE_TOO_LARGE,
    ERR_METHOD_NOT_FOUND,
    ERR_PERMISSION,
    ERR_UNTRUSTED,
    FramingClient,
    FramingError,
    FramingTimeout,
    RpcError,
    TransportClosed,
    runner_socket_path,
)
from _harness.fixtures import runner_config  # noqa: E402
from _harness.report import Report  # noqa: E402
from _harness.runner_proc import Runner  # noqa: E402

GENERATED = HERE / "generated"
CONFIG_PATH = GENERATED / "conformance.toml"
DENY_CONFIG_PATH = GENERATED / "conformance_deny.toml"
ALLOW_CONFIG_PATH = GENERATED / "conformance_allow.toml"
TOKEN_CONFIG_PATH = GENERATED / "conformance_token.toml"
TOKEN = "conformance-secret-token"
RUNNER_MAIN = REPO / "runner" / "__main__.py"
FAKE_PY = REPO / "plugins" / "fake_py" / "plugin.py"
FAKE_RS = REPO / "plugins" / "fake_rs" / "target" / "release" / "fake_rs"


# --------------------------------------------------------------------------- #
# config generation
# --------------------------------------------------------------------------- #
def write_config() -> Path:
    GENERATED.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(runner_config(
        comment="GENERATED by tests/conformance/run.py — do not edit.",
        socket="# Dev override: the conformance client is a same-uid python process. The\n"
               "# default-deny tests below use dedicated configs with allow_binaries/token.\n"
               "allow_same_uid = true",
        confirm_timeout_ms=5000,
        policy='# terminal stays off by default; the suite asserts the disabled path.\n'
               'disabled_ops = ["terminal"]',
    ), encoding="utf-8")
    return CONFIG_PATH


def write_deny_config() -> Path:
    """Default-deny: allow_binaries lists a binary that is NOT our client."""
    GENERATED.mkdir(parents=True, exist_ok=True)
    DENY_CONFIG_PATH.write_text(runner_config(
        comment="GENERATED by tests/conformance/run.py — default-deny probe.",
        socket="# Only this (nonexistent) binary may connect; our python client must be denied.\n"
               'allow_binaries = ["definitely-not-our-client"]',
    ), encoding="utf-8")
    return DENY_CONFIG_PATH


def write_allow_config() -> Path:
    """Allow-list the python interpreter basename so our client is accepted.

    The runner verifies ``/proc/<pid>/exe``, which resolves symlinks, so we must
    list the *real* interpreter basename (e.g. ``python3.14``), not ``python``.
    """
    GENERATED.mkdir(parents=True, exist_ok=True)
    py_name = Path(os.path.realpath(sys.executable)).name
    ALLOW_CONFIG_PATH.write_text(runner_config(
        comment="GENERATED by tests/conformance/run.py — allow-list probe.",
        socket=f'allow_binaries = ["{py_name}"]',
    ), encoding="utf-8")
    return ALLOW_CONFIG_PATH


def write_token_config() -> Path:
    """Token auth: same-uid client must call runner.auth with the token."""
    GENERATED.mkdir(parents=True, exist_ok=True)
    TOKEN_CONFIG_PATH.write_text(runner_config(
        comment="GENERATED by tests/conformance/run.py — token-auth probe.",
        socket=f'token = "{TOKEN}"',
    ), encoding="utf-8")
    return TOKEN_CONFIG_PATH


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def plugins_by_id(status: dict) -> dict:
    out = {}
    for p in status.get("plugins", []) or []:
        pid = p.get("id") or p.get("name")
        if pid:
            out[pid] = p
    return out


def find_plugin(status: dict, needle: str) -> dict | None:
    for pid, p in plugins_by_id(status).items():
        if needle in str(pid) or needle in str(p.get("name", "")):
            return p
    return None


def command_results(client: FramingClient, utterance: str, provenance: str = "user") -> dict:
    return client.request("runner.command",
                          {"utterance": utterance, "provenance": provenance})


def _is_not_implemented(exc: RpcError) -> bool:
    return exc.code == ERR_METHOD_NOT_FOUND


# --------------------------------------------------------------------------- #
# M0 checks
# --------------------------------------------------------------------------- #
def check_handshake(client: FramingClient, rep: Report) -> None:
    print("\n[handshake / negotiation]")
    status = client.request("runner.status", {})
    plugins = plugins_by_id(status)
    rep.check("runner.status returns plugins", bool(plugins),
              f"ids={sorted(plugins)}")

    py = find_plugin(status, "fake_py")
    rs = find_plugin(status, "fake_rs")
    rep.check("fake_py handshaken", py is not None)
    rep.check("fake_rs handshaken (cross-language)", rs is not None)

    if py:
        rep.check("fake_py status ok", py.get("status") in ("ok", "degraded"),
                  f"status={py.get('status')}")
        rep.check("fake_py has epoch", py.get("epoch") is not None,
                  f"epoch={py.get('epoch')}")
        provides = set(py.get("provides", []) or [])
        requires = set(py.get("requires", []) or [])
        rep.check("fake_py provides∩requires non-empty",
                  bool(provides & requires),
                  f"intersection={sorted(provides & requires)}")
        rep.check("fake_py provides router/action caps",
                  any(c.startswith("action.") for c in provides),
                  f"provides={sorted(provides)}")

    rep.check("unknown-capability tolerated (handshake succeeded)", py is not None,
              "experimental/* caps accepted without error")

    # A missing require is an error (fail closed). Asserted against the runner's
    # own validator via a subprocess probe so we do not import runner code.
    probe = subprocess.run(
        [sys.executable, "-c", (
            "import sys; sys.path.insert(0, '.');"
            "from runner.plugin import validate_capabilities;"
            "from runner.rpc import RpcError;"
            "\ntry:\n"
            "    validate_capabilities(['action.open_url@1'], ['does.not.exist@1'])\n"
            "    print('NO_ERROR')\n"
            "except RpcError as e:\n"
            "    print('ERROR', e.code)\n"
        )],
        cwd=str(REPO), capture_output=True, text=True, timeout=15,
    )
    out = (probe.stdout or "").strip()
    rep.check("missing-require rejected (fail closed)",
              out.startswith("ERROR"),
              f"validator said: {out or probe.stderr.strip()[:120]}")


def check_vertical_slice(client: FramingClient, rep: Report) -> None:
    print("\n[vertical slice: runner.command 'open youtube']")
    try:
        res = command_results(client, "open youtube", "user")
    except RpcError as exc:
        rep.check("runner.command open youtube", False, f"error {exc.code}: {exc.message}")
        return
    results = res.get("results", []) if isinstance(res, dict) else []
    rep.check("command returned results", bool(results), f"results={results}")
    if not results:
        return
    first = results[0]
    rep.check("first result ok", first.get("ok") is True, f"op={first.get('op')}")
    rep.check("first result op is ensure_url", first.get("op") == "ensure_url",
              f"op={first.get('op')}")
    detail = str(first.get("detail", ""))
    rep.check("detail mentions youtube", "youtube" in detail.lower(), detail)


def check_policy(client: FramingClient, rep: Report) -> None:
    print("\n[policy: provenance + confirmation]")
    try:
        res = command_results(client, "run rm -rf /", "screen")
        results = res.get("results", []) if isinstance(res, dict) else []
        codes = [r.get("error", {}).get("code") for r in results]
        rep.check("screen-provenance terminal rejected -32006",
                  ERR_UNTRUSTED in codes, f"results={results}")
    except RpcError as exc:
        rep.check("screen-provenance terminal rejected -32006",
                  exc.code == ERR_UNTRUSTED, f"error={exc.code} {exc.message}")

    try:
        res = command_results(client, "run rm -rf /", "user")
        results = res.get("results", []) if isinstance(res, dict) else []
        codes = [r.get("error", {}).get("code") for r in results]
        rep.check("user-provenance terminal denied by policy -32003",
                  ERR_PERMISSION in codes, f"results={results}")
    except RpcError as exc:
        rep.check("user-provenance terminal denied by policy -32003",
                  exc.code == ERR_PERMISSION, f"error={exc.code} {exc.message}")

    confirmed: list[dict] = []

    def on_server_request(method, params, req_id):
        if method == "host.confirm":
            confirmed.append(params or {})
            return {"approved": True}
        raise RpcError(ERR_METHOD_NOT_FOUND, f"no handler for {method}")

    conf_client = FramingClient.connect_unix(runner_socket_path(), timeout=15.0,
                                             request_handler=on_server_request)
    try:
        res = conf_client.request("runner.command",
                                  {"utterance": "run echo hi", "provenance": "user"})
        results = res.get("results", []) if isinstance(res, dict) else []
        rep.check("confirmation path reachable (host.confirm or policy denial)",
                  bool(confirmed) or bool(results),
                  f"confirmed={len(confirmed)} results={results}")
    except RpcError as exc:
        rep.check("confirmation path reachable (host.confirm or policy denial)",
                  True, f"policy denied before confirm: {exc.code}")
    finally:
        conf_client.close()


def check_cross_language(client: FramingClient, rep: Report) -> None:
    print("\n[cross-language: Rust fake]")
    status = client.request("runner.status", {})
    rs = find_plugin(status, "fake_rs")
    rep.check("fake_rs present in status", rs is not None)
    if rs:
        rep.check("fake_rs epoch recorded", rs.get("epoch") is not None,
                  f"epoch={rs.get('epoch')}")
        rep.check("fake_rs status ok", rs.get("status") in ("ok", "degraded"),
                  f"status={rs.get('status')}")
        rep.check("fake_rs provides action cap",
                  any(c.startswith("action.") for c in (rs.get("provides") or [])),
                  f"provides={rs.get('provides')}")


# --------------------------------------------------------------------------- #
# M1 checks
# --------------------------------------------------------------------------- #
def check_backpressure_e2e(client: FramingClient, rep: Report) -> None:
    """(1) End-to-end lossy backpressure through the runner."""
    print("\n[M1.1 end-to-end backpressure through the runner]")
    try:
        sub = client.subscribe("fake.frames", {"rate": "max"}, mode="lossy", timeout=5.0)
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("e2e lossy backpressure", f"runner has no stream.subscribe ({exc.code})")
            return
        rep.check("e2e lossy backpressure", False, f"error {exc.code}: {exc.message}")
        return
    except (FramingTimeout, TransportClosed) as exc:
        rep.skip("e2e lossy backpressure", f"stream.subscribe timed out: {exc}")
        return

    stream_id = str(sub.get("stream_id") or "")
    rep.check("stream.subscribe returns stream_id", bool(stream_id), f"sub={sub}")
    rep.check("stream.subscribe reports mode", sub.get("mode") in ("lossy", None),
              f"mode={sub.get('mode')}")

    # Deliberately slow consumer with a bounded read budget (drop-oldest).
    seqs: list[int] = []
    responsive = 0
    t_end = time.monotonic() + 1.5
    while time.monotonic() < t_end:
        time.sleep(0.05)
        notes = client.drain_notifications(timeout=0.01)
        batch = [int((n.get("params") or {}).get("seq") or 0)
                 for n in notes
                 if (n.get("params") or {}).get("stream_id") == stream_id
                 and "seq" in (n.get("params") or {})]
        if len(batch) > 4:
            batch = batch[-4:]  # drop-oldest
        seqs.extend(batch)
        t0 = time.perf_counter()
        try:
            client.request("runner.status", {}, timeout=2.0)
            if (time.perf_counter() - t0) < 1.0:
                responsive += 1
        except (RpcError, FramingTimeout, TransportClosed):
            pass

    gaps = sum(1 for a, b in zip(seqs, seqs[1:]) if b > a + 1)
    rep.check("(a) other RPCs stay responsive while streaming", responsive > 0,
              f"status_calls={responsive}")
    rep.check("(b) drop-oldest with seq gaps", gaps > 0,
              f"frames={len(seqs)} gaps={gaps}")

    # (c) stream.stop idempotent
    try:
        client.stop_stream(stream_id, timeout=5.0)
        client.stop_stream(stream_id, timeout=5.0)  # second call must not raise
        rep.check("(c) stream.stop idempotent", True, "two stops accepted")
    except RpcError as exc:
        rep.check("(c) stream.stop idempotent", False, f"error {exc.code}: {exc.message}")
    except (FramingTimeout, TransportClosed) as exc:
        rep.check("(c) stream.stop idempotent", False, str(exc))


def check_reliable_flow(client: FramingClient, rep: Report) -> None:
    """(2) Reliable flow control: pause on credit exhaustion, resume on ack."""
    print("\n[M1.2 reliable flow control]")
    try:
        sub = client.subscribe("fake.frames", {}, mode="reliable", timeout=5.0)
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("reliable flow control", f"runner has no stream.subscribe ({exc.code})")
            return
        rep.check("reliable flow control", False, f"error {exc.code}: {exc.message}")
        return
    except (FramingTimeout, TransportClosed) as exc:
        rep.skip("reliable flow control", f"stream.subscribe timed out: {exc}")
        return

    stream_id = str(sub.get("stream_id") or "")
    rep.check("reliable subscribe reports mode", sub.get("mode") in ("reliable", None),
              f"mode={sub.get('mode')}")

    # Consume without acking: the server should pause at the credit window.
    first = client.collect_stream(stream_id, duration=0.6)
    first_seqs = [int((n.get("params") or {}).get("seq") or 0) for n in first]
    max_before = max(first_seqs) if first_seqs else 0
    rep.check("reliable stream delivers frames", max_before > 0,
              f"frames={len(first_seqs)} max_seq={max_before}")

    # No acks -> the producer must pause (seq stops advancing).
    time.sleep(0.4)
    paused = client.collect_stream(stream_id, duration=0.3)
    paused_seqs = [int((n.get("params") or {}).get("seq") or 0) for n in paused]
    max_paused = max(paused_seqs) if paused_seqs else max_before
    rep.check("server pauses when credits exhausted", max_paused <= max_before + 2,
              f"max_before={max_before} max_after_pause={max_paused}")

    # Ack the highest seq -> credit replenished -> stream resumes.
    try:
        client.ack(stream_id, max_paused, timeout=5.0)
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("reliable resume after ack", f"runner has no stream.ack ({exc.code})")
            client.stop_stream(stream_id)
            return
        rep.check("reliable resume after ack", False, f"ack error {exc.code}: {exc.message}")
        client.stop_stream(stream_id)
        return
    resumed = client.collect_stream(stream_id, duration=0.5)
    resumed_seqs = [int((n.get("params") or {}).get("seq") or 0) for n in resumed]
    max_resumed = max(resumed_seqs) if resumed_seqs else max_paused
    rep.check("stream resumes after stream.ack", max_resumed > max_paused,
              f"max_paused={max_paused} max_resumed={max_resumed}")
    client.stop_stream(stream_id)


def check_runner_invoke(client: FramingClient, rep: Report) -> None:
    """(3) runner.invoke: cross-language action + router.plan + provenance."""
    print("\n[M1.3 runner.invoke]")
    # Cross-language: invoke fake_rs's action.invoke.
    try:
        res = client.invoke("fake_rs", "action.invoke",
                            {"op": "ensure_url",
                             "args": {"url": "https://www.youtube.com"},
                             "provenance": "user"}, timeout=10.0)
        rep.check("runner.invoke fake_rs action.invoke ok",
                  isinstance(res, dict) and res.get("ok") is True, f"result={res}")
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("runner.invoke fake_rs", f"runner has no runner.invoke ({exc.code})")
        else:
            rep.check("runner.invoke fake_rs action.invoke ok", False,
                      f"error {exc.code}: {exc.message}")
    except (FramingTimeout, TransportClosed) as exc:
        rep.skip("runner.invoke fake_rs", f"timed out: {exc}")

    # fake_py router.plan through the runner.
    try:
        res = client.invoke("fake_py", "router.plan",
                            {"utterance": "open youtube", "provenance": "user"},
                            timeout=10.0)
        steps = (res or {}).get("steps") if isinstance(res, dict) else None
        rep.check("runner.invoke fake_py router.plan returns steps",
                  bool(steps), f"result={res}")
        if steps:
            rep.check("router.plan step is ensure_url",
                      steps[0].get("op") == "ensure_url", f"step={steps[0]}")
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("runner.invoke fake_py router.plan",
                     f"runner has no runner.invoke ({exc.code})")
        else:
            rep.check("runner.invoke fake_py router.plan returns steps", False,
                      f"error {exc.code}: {exc.message}")
    except (FramingTimeout, TransportClosed) as exc:
        rep.skip("runner.invoke fake_py router.plan", f"timed out: {exc}")

    # Provenance enforcement through runner.invoke: screen-authored terminal args.
    try:
        res = client.invoke("fake_py", "action.invoke",
                            {"op": "terminal", "args": {"command": "rm -rf /"},
                             "provenance": "screen"}, timeout=10.0)
        # If the runner returns a result, it must not be ok.
        ok = isinstance(res, dict) and res.get("ok") is True
        rep.check("runner.invoke screen terminal rejected", not ok, f"result={res}")
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("runner.invoke provenance enforcement",
                     f"runner has no runner.invoke ({exc.code})")
        else:
            rep.check("runner.invoke screen terminal rejected",
                      exc.code == ERR_UNTRUSTED, f"error={exc.code} {exc.message}")
    except (FramingTimeout, TransportClosed) as exc:
        rep.skip("runner.invoke provenance enforcement", f"timed out: {exc}")


def check_validate_plugin(client: FramingClient, rep: Report) -> None:
    """(4) runner.validate_plugin: warnings, missing requires, permissions."""
    print("\n[M1.4 runner.validate_plugin]")
    try:
        res = client.validate_plugin("fake_py", timeout=10.0)
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("runner.validate_plugin", f"runner has no validate_plugin ({exc.code})")
            return
        rep.check("runner.validate_plugin", False, f"error {exc.code}: {exc.message}")
        return
    except (FramingTimeout, TransportClosed) as exc:
        rep.skip("runner.validate_plugin", f"timed out: {exc}")
        return

    rep.check("validate_plugin returns ok", res.get("ok") is True, f"result={res}")
    rep.check("validate_plugin reports negotiated protocol",
              bool((res.get("negotiated") or {}).get("protocol")),
              f"negotiated={res.get('negotiated')}")
    unknown = res.get("unknown_capabilities")
    rep.check("validate_plugin reports unknown_capabilities list",
              isinstance(unknown, list), f"unknown={unknown}")
    rep.check("validate_plugin reports missing_requires list",
              isinstance(res.get("missing_requires"), list),
              f"missing={res.get('missing_requires')}")
    perms = res.get("permissions")
    rep.check("validate_plugin reports per-permission enforced|advisory",
              isinstance(perms, list) and all("enforced" in p for p in perms),
              f"permissions={perms}")

    # A plugin with a missing require must be reported as an error.
    try:
        bad = client.validate_plugin("does_not_exist", timeout=10.0)
        rep.check("validate_plugin unknown plugin -> ok false",
                  bad.get("ok") is False, f"result={bad}")
    except RpcError as exc:
        rep.check("validate_plugin unknown plugin -> error",
                  exc.code in (ERR_METHOD_NOT_FOUND, -32005, -32602),
                  f"error={exc.code} {exc.message}")
    except (FramingTimeout, TransportClosed) as exc:
        rep.skip("validate_plugin unknown plugin", f"timed out: {exc}")


def check_handles_fd(client: FramingClient, rep: Report) -> None:
    """(5) Handles + fd.pass through the runner.

    The runner's handle store is populated internally; there is no client-facing
    ``handle.create`` yet, so the full inline-fetch / fd.pass round trip cannot
    be seeded from the conformance client. We assert the endpoints exist and
    behave correctly for unknown handles, and exercise the SCM_RIGHTS mechanism
    independently over a socketpair.
    """
    print("\n[M1.5 handles + fd.pass through the runner]")

    # Probe handle.fetch with a synthetic (unknown) handle: the endpoint must
    # exist and reject it as a handle error, not method-not-found.
    synthetic = "handle://" + hashlib.sha256(b"conformance").hexdigest()
    try:
        client.handle_fetch(synthetic, timeout=10.0)
        rep.check("handle.fetch endpoint exists", False,
                  "unknown handle unexpectedly fetched")
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("handle.fetch endpoint", f"runner has no handle.fetch ({exc.code})")
        else:
            rep.check("handle.fetch endpoint exists (unknown handle rejected)",
                      exc.code in (-32000, -32602, -32003),
                      f"error={exc.code} {exc.message}")
    except (FramingTimeout, TransportClosed) as exc:
        rep.skip("handle.fetch endpoint", f"timed out: {exc}")

    # handle.stat endpoint.
    try:
        client.request("handle.stat", {"handle": synthetic}, timeout=10.0)
        rep.check("handle.stat endpoint exists", False, "unknown handle statted")
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("handle.stat endpoint", f"runner has no handle.stat ({exc.code})")
        else:
            rep.check("handle.stat endpoint exists (unknown handle rejected)",
                      exc.code in (-32000, -32602, -32003),
                      f"error={exc.code} {exc.message}")
    except (FramingTimeout, TransportClosed) as exc:
        rep.skip("handle.stat endpoint", f"timed out: {exc}")

    # fd.pass endpoint: kind=handle with an unknown handle must be rejected.
    try:
        client.fd_pass("handle", {"handle": synthetic}, timeout=10.0)
        rep.check("fd.pass endpoint exists", False, "unknown handle passed")
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("fd.pass endpoint", f"runner has no fd.pass ({exc.code})")
        else:
            rep.check("fd.pass endpoint exists (unknown handle rejected)",
                      exc.code in (-32000, -32602, -32003),
                      f"error={exc.code} {exc.message}")
    except (FramingTimeout, TransportClosed) as exc:
        rep.skip("fd.pass endpoint", f"timed out: {exc}")

    # SCM_RIGHTS mechanism: independent socketpair round trip (proves the
    # client-side fd.pass/recv_fds implementation is correct).
    try:
        a, b = FramingClient.socketpair(timeout=5.0)
        try:
            fd = os.memfd_create("conformance-fd", 0)
            os.write(fd, b"scm-rights-payload")
            os.lseek(fd, 0, 0)
            a.send_fd_frame("memfd", {"data": "scm-rights-payload"}, fds=[fd])
            os.close(fd)
            _data, fds = b.recv_fds(timeout=3.0)
            ok = bool(fds) and os.read(fds[0], 64) == b"scm-rights-payload"
            for f in fds:
                os.close(f)
            rep.check("SCM_RIGHTS fd round trip (socketpair)", ok, f"fds={len(fds)}")
        finally:
            a.close()
            b.close()
    except (OSError, FramingError) as exc:
        rep.skip("SCM_RIGHTS fd round trip", f"not supported: {exc}")

    # -- end-to-end: handle.create → handle.fetch inline -------------------- #
    payload = b"utter inline handle \x00\x01\x02"
    created = None
    try:
        created = client.request(
            "handle.create",
            {"data_b64": base64.b64encode(payload).decode("ascii")},
            timeout=10.0,
        )
        rep.check("handle.create returns handle/sha256/size",
                  bool(created.get("handle")) and created.get("size") == len(payload),
                  f"result={created}")
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("handle.create", f"runner has no handle.create ({exc.code})")
        else:
            rep.check("handle.create returns handle/sha256/size", False,
                      f"error {exc.code}: {exc.message}")
    except (FramingTimeout, TransportClosed) as exc:
        rep.skip("handle.create", f"timed out: {exc}")

    if created and created.get("handle"):
        try:
            fetched = client.handle_fetch(created["handle"], timeout=10.0)
            data = base64.b64decode(fetched.get("data_b64", ""))
            digest = hashlib.sha256(data).hexdigest()
            rep.check("handle.fetch inline sha256 matches created content",
                      digest == created.get("sha256") == hashlib.sha256(payload).hexdigest(),
                      f"sha256={digest}")
            rep.check("handle.fetch inline size correct",
                      fetched.get("size") == len(payload),
                      f"size={fetched.get('size')} expected={len(payload)}")
        except RpcError as exc:
            rep.check("handle.fetch inline sha256 matches created content", False,
                      f"error {exc.code}: {exc.message}")
        except (FramingTimeout, TransportClosed) as exc:
            rep.skip("handle.fetch inline", f"timed out: {exc}")

    # -- end-to-end: >64 KiB handle → -32007 -------------------------------- #
    try:
        big = client.request("handle.create", {"size": 128 * 1024}, timeout=10.0)
        big_handle = big.get("handle")
        rep.check("handle.create large (128 KiB)", bool(big_handle),
                  f"size={big.get('size')}")
        if big_handle:
            try:
                client.handle_fetch(big_handle, timeout=10.0)
                rep.check("handle.fetch >64KiB rejected -32007", False,
                          "fetch unexpectedly succeeded")
            except RpcError as exc:
                rep.check("handle.fetch >64KiB rejected -32007",
                          exc.code == ERR_HANDLE_TOO_LARGE,
                          f"error={exc.code} {exc.message}")
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("handle.fetch >64KiB rejected -32007",
                     f"runner has no handle.create ({exc.code})")
        else:
            rep.check("handle.fetch >64KiB rejected -32007", False,
                      f"error {exc.code}: {exc.message}")
    except (FramingTimeout, TransportClosed) as exc:
        rep.skip("handle.fetch >64KiB rejected -32007", f"timed out: {exc}")

    # -- end-to-end: fd.pass kind="handle" over the socket transport -------- #
    if created and created.get("handle"):
        try:
            result, fds = client.fd_pass_recv("handle", {"handle": created["handle"]},
                                              timeout=10.0)
            rep.check("fd.pass kind=handle returns {}", result == {}, f"result={result}")
            rep.check("fd.pass kind=handle delivers exactly one fd", len(fds) == 1,
                      f"fds={len(fds)}")
            if fds:
                content = os.read(fds[0], 4096)
                rep.check("fd.pass kind=handle content matches",
                          content == payload, f"content={content!r}")
                for f in fds:
                    os.close(f)
        except RpcError as exc:
            if _is_not_implemented(exc):
                rep.skip("fd.pass kind=handle", f"runner has no fd.pass ({exc.code})")
            else:
                rep.check("fd.pass kind=handle returns {}", False,
                          f"error {exc.code}: {exc.message}")
        except (FramingTimeout, TransportClosed, OSError) as exc:
            rep.skip("fd.pass kind=handle", f"not supported: {exc}")

    # -- end-to-end: fd.pass kind="memfd" (plain memfd, not a true ring) ---- #
    try:
        result, fds = client.fd_pass_recv("memfd", {"data": "memfd-payload", "size": 4096},
                                          timeout=10.0)
        # kind=handle returns {}; kind=memfd returns its geometry metadata.
        rep.check("fd.pass kind=memfd returns metadata",
                  isinstance(result, dict) and result.get("kind") == "memfd",
                  f"result={result}")
        rep.check("fd.pass kind=memfd delivers exactly one fd", len(fds) == 1,
                  f"fds={len(fds)}")
        if fds:
            content = os.read(fds[0], 64)
            rep.check("fd.pass kind=memfd content matches",
                      content.startswith(b"memfd-payload"), f"content={content[:32]!r}")
            for f in fds:
                os.close(f)
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("fd.pass kind=memfd", f"runner has no fd.pass memfd ({exc.code})")
        else:
            rep.check("fd.pass kind=memfd returns metadata", False,
                      f"error {exc.code}: {exc.message}")
    except (FramingTimeout, TransportClosed, OSError) as exc:
        rep.skip("fd.pass kind=memfd", f"not supported: {exc}")

    # memfd.ring is a plain memfd in the runner (not a true ring buffer), so
    # ring semantics (wrap-around / read-write cursors) are not testable yet.
    rep.skip("memfd.ring wrap-around semantics",
             "runner memfd.ring is a plain memfd, not a true ring buffer")


def check_socket_default_deny(rep: Report) -> None:
    """(6) Socket default-deny: unlisted client rejected, allow-listed accepted."""
    print("\n[M1.6 socket default-deny]")
    deny_sock = str(GENERATED / "runner-deny.sock")
    allow_sock = str(GENERATED / "runner-allow.sock")

    # Default-deny: allow_binaries lists a binary that is not our client.
    deny = Runner(timeout=20.0, config=write_deny_config(), log_dir=GENERATED,
                  sock_path=deny_sock, log_name="runner-deny.log")
    try:
        deny.start()
        if not deny.wait_ready():
            rep.skip("socket default-deny", "deny-config runner did not start")
        else:
            try:
                c = FramingClient.connect_unix(deny_sock, timeout=5.0)
                try:
                    c.request("runner.status", {}, timeout=3.0)
                    rep.check("unlisted client rejected", False,
                              "connection was accepted and served")
                except (TransportClosed, FramingTimeout, OSError):
                    rep.check("unlisted client rejected", True,
                              "connection closed / no response")
                finally:
                    c.close()
            except OSError as exc:
                rep.check("unlisted client rejected", True, f"connect refused: {exc}")
    finally:
        deny.stop()

    # Allow-list: our interpreter basename is permitted.
    allow = Runner(timeout=20.0, config=write_allow_config(), log_dir=GENERATED,
                   sock_path=allow_sock, log_name="runner-allow.log")
    try:
        allow.start()
        if not allow.wait_ready():
            rep.skip("socket allow-list accepted", "allow-config runner did not start")
        else:
            try:
                c = FramingClient.connect_unix(allow_sock, timeout=5.0)
                try:
                    status = c.request("runner.status", {}, timeout=5.0)
                    rep.check("allow-listed client accepted",
                              bool(status.get("plugins")), f"plugins={len(status.get('plugins', []))}")
                finally:
                    c.close()
            except (RpcError, TransportClosed, FramingTimeout, OSError) as exc:
                rep.check("allow-listed client accepted", False, str(exc))
    finally:
        allow.stop()

    # Token auth: same-uid client must call runner.auth before other methods.
    token_sock = str(GENERATED / "runner-token.sock")
    tok = Runner(timeout=20.0, config=write_token_config(), log_dir=GENERATED,
                 sock_path=token_sock, log_name="runner-token.log")
    try:
        tok.start()
        if not tok.wait_ready():
            rep.skip("socket token auth", "token-config runner did not start")
        else:
            try:
                c = FramingClient.connect_unix(token_sock, timeout=5.0)
                try:
                    # Unauthenticated call must be denied.
                    try:
                        c.request("runner.status", {}, timeout=3.0)
                        rep.check("token: unauthenticated call denied", False,
                                  "call succeeded without auth")
                    except RpcError as exc:
                        rep.check("token: unauthenticated call denied",
                                  exc.code == ERR_PERMISSION,
                                  f"error={exc.code} {exc.message}")
                    # Authenticate, then the call must succeed.
                    c.auth(TOKEN, timeout=3.0)
                    status = c.request("runner.status", {}, timeout=5.0)
                    rep.check("token: authenticated call accepted",
                              bool(status.get("plugins")),
                              f"plugins={len(status.get('plugins', []))}")
                finally:
                    c.close()
            except (RpcError, TransportClosed, FramingTimeout, OSError) as exc:
                rep.check("token: authenticated call accepted", False, str(exc))
    finally:
        tok.stop()


def check_memfd_ring(client: FramingClient, rep: Report) -> None:
    """(7) Memfd ring buffer round trip (if implemented)."""
    print("\n[M1.7 memfd ring buffer]")
    try:
        res = client.invoke("fake_py", "memfd.ring", {"size": 4096}, timeout=10.0)
        if isinstance(res, dict) and res.get("ok"):
            rep.check("memfd ring created", res.get("size") == 4096, f"result={res}")
            # Exercise a real fd round trip over a socketpair (independent of the
            # runner): send a memfd and read it back.
            a, b = FramingClient.socketpair(timeout=5.0)
            try:
                fd = os.memfd_create("ring-test", 0)
                os.ftruncate(fd, 4096)
                os.write(fd, b"ring-data")
                os.lseek(fd, 0, 0)
                a.send_fd_frame("memfd.ring", {"size": 4096}, fds=[fd])
                os.close(fd)
                data, fds = b.recv_fds(timeout=3.0)
                ok = bool(fds) and os.read(fds[0], 64).startswith(b"ring-data")
                for f in fds:
                    os.close(f)
                rep.check("memfd fd round trip (SCM_RIGHTS)", ok,
                          f"fds={len(fds)}")
            finally:
                a.close()
                b.close()
        else:
            rep.skip("memfd ring", f"fake reports not supported: {res}")
    except RpcError as exc:
        if _is_not_implemented(exc):
            rep.skip("memfd ring", f"runner has no runner.invoke ({exc.code})")
        else:
            rep.check("memfd ring created", False, f"error {exc.code}: {exc.message}")
    except (FramingTimeout, TransportClosed, OSError) as exc:
        rep.skip("memfd ring", f"not supported: {exc}")


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="utter M0/M1 conformance suite")
    ap.add_argument("--timeout", type=float, default=30.0)
    ap.add_argument("--keep", action="store_true", help="leave the runner running")
    args = ap.parse_args(argv)

    print("utter M0/M1 conformance suite")
    print(f"  repo:   {REPO}")
    print(f"  socket: {runner_socket_path()}")

    if not RUNNER_MAIN.exists():
        print("\nBLOCKED: runner/__main__.py is not present.")
        print(f"  expected: {RUNNER_MAIN}")
        return 2

    if not FAKE_RS.exists():
        print(f"\nBLOCKED: Rust fake not built: {FAKE_RS}")
        print("  run: cargo build --release --manifest-path plugins/fake_rs/Cargo.toml")
        return 2

    config = write_config()
    print(f"  config: {config}")

    runner = Runner(config=config, sock_path=runner_socket_path(),
                    log_dir=GENERATED, timeout=args.timeout)
    rep = Report(skip_label="NOT-YET-SUPPORTED: ")
    client = None
    try:
        runner.start()
        if not runner.wait_ready():
            print("\nBLOCKED: runner did not become ready.")
            print("--- runner log tail ---")
            print(runner.tail_log())
            return 2
        client = runner.connect()
        # M0
        check_handshake(client, rep)
        check_vertical_slice(client, rep)
        check_policy(client, rep)
        check_cross_language(client, rep)
        # M1
        check_backpressure_e2e(client, rep)
        check_reliable_flow(client, rep)
        check_runner_invoke(client, rep)
        check_validate_plugin(client, rep)
        check_handles_fd(client, rep)
        check_memfd_ring(client, rep)
    except (FramingTimeout, TransportClosed, OSError) as exc:
        print(f"\nBLOCKED: transport error: {exc}")
        print("--- runner log tail ---")
        print(runner.tail_log())
        return 2
    finally:
        if client is not None:
            client.close()
        if not args.keep:
            runner.stop()

    # Socket default-deny needs its own runner instances; run after the main one.
    check_socket_default_deny(rep)

    summary = rep.summary()
    print(f"\n=== {summary['passed']}/{summary['total']} checks passed, "
          f"{summary['skipped']} not-yet-supported ===")
    if rep.failed:
        print("FAILED:")
        for c in rep.failed:
            print(f"  - {c['name']}: {c['detail']}")
        return 1
    if rep.skips:
        print("NOT-YET-SUPPORTED (runner M1 features pending):")
        for s in rep.skips:
            print(f"  - {s['name']}: {s['reason']}")
    print("ALL ASSERTIONS PASSED")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
