#!/usr/bin/env python3
"""Guard: provenance invariant for ``action.invoke`` (TRUST.md §1).

Table-driven: every op carrying a concrete arg with ``provenance: "screen"``
must be rejected by the runner with ``-32006``. A ``user`` call is never
rejected as untrusted (positive control). Runs the runner with the fake_py
plugin, hermetically.
"""
from __future__ import annotations

import os
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))
sys.path.insert(0, str(ROOT / "tests" / "conformance"))

from framing_client import RpcError  # noqa: E402
from _harness.fixtures import runner_config  # noqa: E402
from _harness.runner_proc import Runner  # noqa: E402

UNTRUSTED_ARG = -32006

# One row per op in runner/policy.py DEFAULT_OPS that has concrete_args.
CASES = [
    ("ensure_url", {"url": "https://example.com"}),
    ("open_url", {"url": "https://example.com"}),
    ("terminal", {"command": "rm -rf /"}),
    ("input", {"text": "hello"}),
    ("niri", {"command": "move-column-right"}),
    ("launch_app", {"app_id": "firefox"}),
]


class TestProvenanceInvariant(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = Path(tempfile.mkdtemp(prefix="utter-provenance-"))
        os.environ.setdefault("XDG_RUNTIME_DIR", str(cls.tmp))
        (Path(os.environ["XDG_RUNTIME_DIR"]) / "utter").mkdir(parents=True, exist_ok=True)
        config = cls.tmp / "provenance.toml"
        config.write_text(runner_config(
            comment="GENERATED by tests/test_provenance_invariant.py — do not edit.",
            socket="allow_same_uid = true",
        ), encoding="utf-8")
        cls.runner = Runner(config=config, sock_path=str(cls.tmp / "runner.sock"),
                            log_dir=cls.tmp, log_name="runner.log")
        cls.runner.start()
        cls.ready = cls.runner.wait_ready()

    @classmethod
    def tearDownClass(cls):
        cls.runner.stop()

    def setUp(self):
        if not self.ready:
            self.fail("runner did not start:\n" + self.runner.tail_log())

    def _invoke(self, op: str, args: dict, provenance: str):
        """Return ``("ok", result)`` or ``("error", code, message)``."""
        client = self.runner.connect()
        try:
            res = client.invoke("fake_py", "action.invoke",
                                {"op": op, "args": args, "provenance": provenance},
                                timeout=10.0)
            return ("ok", res)
        except RpcError as exc:
            return ("error", exc.code, exc.message)
        finally:
            client.close()

    def test_screen_cannot_author_args(self):
        for op, args in CASES:
            with self.subTest(op=op):
                kind, *rest = self._invoke(op, args, "screen")
                self.assertEqual(kind, "error", f"screen {op} was not rejected: {rest}")
                self.assertEqual(rest[0], UNTRUSTED_ARG,
                                 f"screen {op} rejected with {rest[0]}, want {UNTRUSTED_ARG}")

    def test_user_is_never_rejected_as_untrusted(self):
        for op, args in CASES:
            with self.subTest(op=op):
                kind, *rest = self._invoke(op, args, "user")
                if kind == "error":
                    self.assertNotEqual(rest[0], UNTRUSTED_ARG,
                                        f"user {op} wrongly rejected as untrusted")


if __name__ == "__main__":
    unittest.main()
